from django.db import models


class WatchlistEntry(models.Model):
    """Entity on the firm's internal watchlist for ongoing monitoring."""

    REASON_CHOICES = [
        ('sanctions',    'Sanctions Concern'),
        ('pep',          'Politically Exposed Person'),
        ('adverse_media','Adverse Media'),
        ('credit_risk',  'Credit Risk'),
        ('fraud',        'Fraud Concern'),
        ('regulatory',   'Regulatory Flag'),
        ('other',        'Other'),
    ]
    STATUS_CHOICES = [
        ('active',   'Active'),
        ('resolved', 'Resolved'),
        ('escalated','Escalated'),
    ]

    entity_name  = models.CharField(max_length=255)
    entity_type  = models.CharField(max_length=50, blank=True)
    country      = models.CharField(max_length=100, blank=True)
    reason       = models.CharField(max_length=20, choices=REASON_CHOICES)
    status       = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active')
    detail       = models.TextField(blank=True)
    added_by     = models.CharField(max_length=255, blank=True)
    added_at     = models.DateTimeField(auto_now_add=True)
    last_checked = models.DateTimeField(null=True, blank=True)
    resolved_at  = models.DateTimeField(null=True, blank=True)
    resolution   = models.TextField(blank=True)

    class Meta:
        ordering = ['-added_at']

    def __str__(self):
        return f"{self.entity_name} — {self.reason} [{self.status}]"


class ComplianceAlert(models.Model):
    """Alert generated by an automated compliance check."""

    SEVERITY_CHOICES = [
        ('critical', 'Critical'),
        ('high',     'High'),
        ('medium',   'Medium'),
        ('low',      'Low'),
    ]
    STATUS_CHOICES = [
        ('open',         'Open'),
        ('acknowledged', 'Acknowledged'),
        ('resolved',     'Resolved'),
        ('false_positive','False Positive'),
    ]

    alert_type   = models.CharField(max_length=100)
    severity     = models.CharField(max_length=10, choices=SEVERITY_CHOICES)
    status       = models.CharField(max_length=15, choices=STATUS_CHOICES, default='open')
    entity_name  = models.CharField(max_length=255, blank=True)
    title        = models.CharField(max_length=255)
    detail       = models.TextField()
    source       = models.CharField(max_length=100, blank=True)
    assigned_to  = models.CharField(max_length=255, blank=True)
    created_at   = models.DateTimeField(auto_now_add=True)
    resolved_at  = models.DateTimeField(null=True, blank=True)
    notes        = models.TextField(blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"[{self.severity.upper()}] {self.title}"
